INSTALL_ZSH="true"
UPGRADE_PACKAGES="false"
STRUCTURIZR_VERSION=1.15.0
USERNAME=vscode
USER_UID=1000
USER_GID=$USER_UID


/library-scripts/common-debian.sh $INSTALL_ZSH $USERNAME $USER_UID $USER_GID $UPGRADE_PACKAGES